// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkiylTqnH_7XxUM9NT8S0u8v4j0XHmBK4',
    appId: '1:104229536375:android:e8a488f19cee73a540bc72',
    messagingSenderId: '104229536375',
    projectId: 'flashi-13c9b',
    databaseURL: 'https://flashi-13c9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flashi-13c9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkhz8GAq-Sc0pbC45g2eavEyKI_ozTPaw',
    appId: '1:104229536375:ios:fd5e7f2155dc68e040bc72',
    messagingSenderId: '104229536375',
    projectId: 'flashi-13c9b',
    databaseURL: 'https://flashi-13c9b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flashi-13c9b.appspot.com',
    iosClientId: '104229536375-7pneavt2cjepmru7fn6e2pfu2u3pj801.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashiClient',
  );
}
